// Generated content sequence by following frontmatter `next` links starting from milestone-1

export type ContentMetaData = {
  slug: string;
  contentMetaId: string | null;
  programId?: string;
  title: string;
  subtitle?: string;
  pubDate?: string;
  updatedDate?: string;
  description: string;
  sequence?: number;
  contentType: string;
  milestone: string; // milestone slug
};

export const contentSequence: ContentMetaData[] = [

  {// Content sequence generation completed
    slug: "milestone-1-begin-your-thrilling-new-adventure",
    contentMetaId: "33635792-22c0-4c5a-a909-cc290ca2f7c3",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Light Your Spark",
    subtitle: "Begin your thrilling new adventure!",
    pubDate: "2023-10-01",
    updatedDate: "2023-10-05",
    description: "Begin your thrilling entrepreneurial adventure by cultivating the right mindset, setting clear initial goals, and learning to embrace the exciting and challenging path ahead.",
    sequence: 1,
    contentType: "milestones",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "welcome-to-urge",
    contentMetaId: "7ee61551-6c06-4554-b13e-e646043052b5",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Urge: Your Blueprint for Real Business",
    subtitle: "Your Journey Starts Here",
    pubDate: "2024-11-01",
    updatedDate: "2025-07-25",
    description: "Launch your business with Urge! Overcome obstacles, build a strong foundation, and take action. Practical exercises, real-world challenges, and a supportive community await. Start your entrepreneurial journey today!",
    sequence: 1,
    contentType: "concepts",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "understanding-your-entrepreneurial-motivations",
    contentMetaId: "69bf2470-4711-4665-b1d7-927dbf93c694",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Your Fuel",
    subtitle: "Understanding What Drives You",
    pubDate: "2024-11-01",
    updatedDate: "2025-07-25",
    description: "Discover your 'why' for starting a business! Explore common motivations, inspiring stories, and practical exercises to uncover your entrepreneurial drive. Fuel your passion and achieve your dreams with Urge.",
    sequence: 2,
    contentType: "concepts",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "uncover-your-why",
    contentMetaId: "83c3bd5f-ef27-4562-add0-e0956567b2c0",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Find Your Purpose",
    subtitle: "Explore the deeper motivation behind your entrepreneurial journey.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-21",
    description: "Optional description of the exercise",
    sequence: 1,
    contentType: "exercises",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "ready-to-take-the-leap",
    contentMetaId: "a500e26b-8c40-4e79-ad73-6f0591b93b24",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Take the Leap",
    subtitle: "Action Over Perfection",
    pubDate: "2024-11-01",
    updatedDate: "2025-07-25",
    description: "",
    sequence: 3,
    contentType: "concepts",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "bust-the-myths",
    contentMetaId: "1eda17a4-7340-464d-bb7c-8f7e9c19e353",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Reality Check",
    subtitle: "Challenge common myths and gain a clear perspective on business.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-21",
    description: "Optional description of the exercise",
    sequence: 2,
    contentType: "exercises",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "facing-the-fear-of-asking-and-dealing-with-rejection",
    contentMetaId: "9f096b43-720f-4e25-93fe-28b6ec5e5b5a",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Overcoming Rejection",
    subtitle: "Facing Your Fear of Asking",
    pubDate: "2024-11-01",
    updatedDate: "2025-07-25",
    description: "Overcome the fear of asking and rejection with actionable challenges! Build confidence, embrace 'no,' and develop essential entrepreneurial skills through real-life exercises.",
    sequence: 5,
    contentType: "concepts",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "compliment-challenge",
    contentMetaId: "2f23e063-1302-4e8d-97d1-dc6d324522f4",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Give Compliments",
    subtitle: "Overcome hesitation by giving sincere compliments to strangers.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Face the fear of asking and start building confidence with this simple but powerful challenge to give compliments to strangers.",
    sequence: 1,
    contentType: "challenges",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "ask-for-a-favor-challenge",
    contentMetaId: "3c5a4d80-b7ef-41b8-a19b-e920b71ac21c",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Ask for Help",
    subtitle: "Build confidence by stepping outside your comfort zone.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Step outside your comfort zone and ask someone for a favor to build confidence in asking and overcome the fear of rejection.",
    sequence: 2,
    contentType: "challenges",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "the-coffee-shop-discount-challenge",
    contentMetaId: "c0da3e3d-3f98-4a4e-80f4-0d77d39d4e73",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Discount Ask",
    subtitle: "Step outside your comfort zone by asking for a discount.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Boost your confidence by practicing the art of asking, even in the face of potential rejection. Step outside your comfort zone and ask for a discount at a coffee shop to build resilience and embrace discomfort.",
    sequence: 3,
    contentType: "challenges",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "10-nos-challenge",
    contentMetaId: "4d34af9b-ab4e-4490-921f-f98141527269",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "10 Rejections",
    subtitle: "Strengthen resilience by aiming for 10 'No' responses.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Push your boundaries by actively seeking rejection. Aim for 10 'No' responses to requests you make, building resilience and reframing your mindset about rejection.",
    sequence: 4,
    contentType: "challenges",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "start-before-you-are-ready",
    contentMetaId: "c89f82a1-92a0-45f7-85af-5a83d20e99a1",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Action Over Hesitation",
    subtitle: "Start Before You're Ready",
    pubDate: "2024-11-01",
    updatedDate: "2025-07-25",
    description: "Overcome overthinking and embrace action with this empowering activity. Learn how to adopt an experimental mindset, turn failures into feedback, and gain clarity by doing.",
    sequence: 6,
    contentType: "concepts",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "the-5-minute-rule-challenge",
    contentMetaId: "281ecdf7-fdfb-4399-a6a3-9c3480b8657e",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "5-Minute Action",
    subtitle: "Get started by committing to just five minutes of action.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "The hardest part of starting anything is taking the first step. This challenge simplifies the process, allowing you to focus on action without overanalyzing.",
    sequence: 5,
    contentType: "challenges",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "the-worst-case-scenario-challenge",
    contentMetaId: "dc5938b2-533c-4146-a1e0-cbf7f0361174",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Worst-Case Thinking",
    subtitle: "Confront fears by analyzing worst-case scenarios and their impact.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Overthinking often stems from fear of the unknown. This exercise helps you confront your fears, understand their real impact, and reframe them to focus on potential benefits.",
    sequence: 6,
    contentType: "challenges",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "the-just-do-it-day",
    contentMetaId: "4cba35ee-cb84-414b-a556-14d62586e3dd",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Action Day",
    subtitle: "Set aside a dedicated day to take action and build momentum.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Creating a focused window of action reduces procrastination and reinforces the sense of accomplishment. Momentum builds confidence for future tasks.",
    sequence: 7,
    contentType: "challenges",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "accountability-power-up-share-your-goals-and-get-support",
    contentMetaId: "d2e61147-4bba-42e6-9f5e-4b5dccba3fe9",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Accountability Boost",
    subtitle: "Your Secret Weapon for Staying on Track",
    pubDate: "2024-11-01",
    updatedDate: "2025-07-25",
    description: "Boost your entrepreneurial journey with accountability! Learn how to share your goals with friends and family, gain support, and stay motivated with Urge. Discover the power of accountability and unlock your full potential.",
    sequence: 7,
    contentType: "concepts",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "get-your-cheer-squad",
    contentMetaId: "ea9e5f05-487a-477f-bdc5-e572e82afbec",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Build Your Support Network",
    subtitle: "Rally friends and family to support your entrepreneurial path.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Invite your friends and family to be your accountability partners and cheer you on as you build your business.",
    sequence: 3,
    contentType: "exercises",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "entrepreneurial-self-assessment-analyze-your-strengths-and-areas-to-improve",
    contentMetaId: "020bc449-5e61-4e53-931c-b11ae9606614",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Your Entrepreneurial Blueprint",
    subtitle: "Uncovering Your Strengths & Growth Zones",
    pubDate: "2024-11-06",
    updatedDate: "2025-07-25",
    description: "Assess your entrepreneurial strengths and weaknesses with this self-assessment activity. Gain valuable insights into your skills and identify areas for improvement. Start your business journey with self-awareness and a plan for growth.",
    sequence: 8,
    contentType: "concepts",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "entrepreneurial-self-assessment",
    contentMetaId: "ac1d6a67-ad97-475a-9392-14892ab513bc",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Founder Check-In",
    subtitle: "Assess your strengths and areas for entrepreneurial growth.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "This activity is designed to help you reflect on the skills and strengths you already have as an entrepreneur, while also uncovering areas where you can grow.",
    sequence: 4,
    contentType: "exercises",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  },
  {
    slug: "your-skills",
    contentMetaId: null,
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Your Skills",
    subtitle: "",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "This activity is designed to help you reflect on the skills and strengths you already have as an entrepreneur, while also uncovering areas where you can grow.",
    sequence: 4,
    contentType: "concepts",
    milestone: "milestone-1-begin-your-thrilling-new-adventure"
  }
  ,
  // --- Milestone 2: Discovering Opportunities ---
  {
    slug: "milestone-2-discovering-opportunities",
    contentMetaId: "b75e5ca4-1c47-483c-8589-54fac8a58038",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Opportunities",
    subtitle: "Discovering Opportunities",
    pubDate: "2024-11-22",
    updatedDate: "2025-05-22",
    description: " Learn practical and effective methods to identify promising business opportunities by thoroughly exploring problems, observing customer needs, and understanding market dynamics.",
    sequence: 2,
    contentType: "milestones",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "understanding-value",
    contentMetaId: "1b3e53ff-e2db-4478-a05f-111a103d6e18",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "What is Value?",
    subtitle: "The Core of Every Successful Business",
    pubDate: "2024-11-06",
    updatedDate: "2025-07-25",
    description: "Learn the core concept of value in business and how to create products and services customers love. Understand value from both the customer and founder perspective, and discover how successful businesses generate value and profits.",
    sequence: 11,
    contentType: "concepts",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "problems-are-opportunities",
    contentMetaId: "0b20bcfe-3a3c-43d5-a03b-5bc2f5a9eac8",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Problems Are Opportunities",
    subtitle: "Your Blueprint for Unlocking Value",
    pubDate: "2024-11-06",
    updatedDate: "2025-07-25",
    description: "Learn to identify valuable business opportunities by spotting everyday problems! This guide provides practical tips and examples to help you develop a problem-solving mindset and uncover hidden opportunities for innovation.",
    sequence: 12,
    contentType: "concepts",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "practical-approaches-to-discovering-opportunities",
    contentMetaId: "230af613-c323-4f04-b013-59b1a2fbfd79",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Discovering Opportunities",
    subtitle: "The Urge Way to Spot What Sells",
    pubDate: "2024-11-06",
    updatedDate: "2025-07-25",
    description: "Discover practical approaches to finding business opportunities! Learn how to identify problems worth solving by observing your own needs, the needs of those around you, and broader market trends.",
    sequence: 13,
    contentType: "concepts",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "your-problems",
    contentMetaId: "1a758f40-f0e6-4867-984e-8842d675f497",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Your Problems, Your Goldmine",
    subtitle: "Solving Your Own Frustrations (Start with What You Know)",
    pubDate: "2024-11-06",
    updatedDate: "2025-07-25",
    description: "Discover how to identify business opportunities by solving your own problems. Learn practical ways to observe daily frustrations, ask the right questions, and record potential solutions that can lead to a successful business idea.",
    sequence: 14,
    contentType: "concepts",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "identifying-your-problems-and-frustrations",
    contentMetaId: "4cd79489-8507-4a28-9a68-f56ceada5c7c",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Problem Finder",
    subtitle: "Analyze daily frustrations to uncover business potential.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Exercise to document and analyze the problems you face. These will help you reflect on your daily life and uncover frustrations that might lead to a business idea.",
    sequence: 7,
    contentType: "exercises",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "observing-people-around-you",
    contentMetaId: "683d3883-eb00-43cc-b462-df4b39940382",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Observe Your Inner Circle",
    subtitle: "Problems Are Everywhere",
    pubDate: "2024-11-06",
    updatedDate: "2025-07-25",
    description: "Learn how to spot business opportunities by observing the people around you. This activity helps you identify problems in your zone of influence and turn them into potential solutions.",
    sequence: 15,
    contentType: "concepts",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "observing-people-around-you-exercise",
    contentMetaId: "4823e15b-be1d-46b4-b72d-22f60f0f3d80",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Everyday Insights",
    subtitle: "Identify business opportunities by analyzing real-world problems.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Observe and document the problems you observe and analyze their potential as business opportunities.",
    sequence: 8,
    contentType: "exercises",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "putting-your-skills-to-use",
    contentMetaId: "ebe66fa3-4f71-462e-86e2-162d30b78ffa",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Using Your Skills",
    subtitle: "Turn Your Talents into Opportunities",
    pubDate: "2024-11-06",
    updatedDate: "2025-07-25",
    description: "Discover how to turn your skills into a business opportunity! Learn simple ways to identify your talents, evaluate their potential, and create solutions that people value.",
    sequence: 16,
    contentType: "concepts",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "turning-skills-into-opportunities",
    contentMetaId: "3bb039a6-9957-4065-89df-d8e09445db34",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Skill to Startup",
    subtitle: "Leverage your talents to create valuable business ideas.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Let’s explore how to identify your skills and see how they can help others!",
    sequence: 9,
    contentType: "exercises",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "casting-a-wider-net",
    contentMetaId: "11bc6a18-c69f-4c40-87ac-faaa4b6fc66f",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Cast a Wider Net",
    subtitle: "Expanding Your Search for Opportunities",
    pubDate: "2024-11-06",
    updatedDate: "2025-07-25",
    description: "Expanding your search beyond the immediate circle to find more viable opportunities via marketplaces, trends, and niche communities.",
    sequence: 17,
    contentType: "concepts",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "spotting-trends-on-marketplaces",
    contentMetaId: "49c9a421-870b-428c-923e-52466b1d9038",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Marketplace Trends",
    subtitle: "Identify top-selling products and the problems they solve.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Explore platforms like Amazon, Etsy, and eBay to identify popular products, trends, and the problems they solve.",
    sequence: 10,
    contentType: "exercises",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "finding-insights-with-google-trends",
    contentMetaId: "18fb9bce-20d3-4ecf-a778-d5e34b6200b9",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Data-Driven Ideas",
    subtitle: "Use search trends to spot new opportunities.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Use Google Trends to uncover rising topics and identify potential opportunities based on search patterns.",
    sequence: 11,
    contentType: "exercises",
    milestone: "milestone-2-discovering-opportunities"
  },
  {
    slug: "social-media-trendspotting",
    contentMetaId: "9cd253d5-f60c-4cef-8a9d-ad2232d0dfb0",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Viral Insights",
    subtitle: "Discover opportunities through trending hashtags and discussions.",
    pubDate: "2023-10-01",
    updatedDate: "2025-05-22",
    description: "Analyze trending hashtags and comments on platforms like Instagram, Pinterest, and TikTok to identify problems and ideas.",
    sequence: 12,
    contentType: "exercises",
    milestone: "milestone-2-discovering-opportunities"
  },

  // --- Milestone 3: Evaluating Opportunities ---
  {
    slug: "milestone-3-evaluating-opportunities",
    contentMetaId: "ce357a13-22cc-4a37-bde2-05373af390bf",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Evaluation",
    subtitle: "Evaluating and Picking the Right Opportunity",
    pubDate: "2024-11-22",
    updatedDate: "2024-11-22",
    description: "Develop a comprehensive framework to critically assess your identified opportunities, carefully considering market viability, the competitive landscape, and your personal fit to select the best path forward.",
    sequence: 3,
    contentType: "milestones",
    milestone: "milestone-3-evaluating-opportunities"
  },
  {
    slug: "exploring-your-market",
    contentMetaId: "",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Exploring Your Market",
    subtitle: "Understanding Your Target Audience",
    pubDate: "2024-11-06",
    updatedDate: "2025-07-25",
    description: "Learn how to define your target market and conduct effective market research to validate your business ideas.",
    sequence: 22,
    contentType: "concepts",
    milestone: "milestone-3-evaluating-opportunities"
  },
  {
    slug: "research-your-opportunity",
    contentMetaId: "",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Understanding your opportunities",
    subtitle: "Research for your 3 chosen opportunities",
    pubDate: "2024-11-06",
    updatedDate: "2025-07-25",
    description: "Learn how to identify customer pain points, unmet needs, and motivations to create solutions that truly resonate with your target audience.",
    sequence: 23,
    contentType: "exercises",
    milestone: "milestone-3-evaluating-opportunities"
  },
  {
    slug: "deep-dive-into-customer-needs",
    contentMetaId: "",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Deep Dive into Customer Needs",
    subtitle: "Uncovering Pains, Gains, and Motivations",
    description: "Learn how to identify customer pain points, unmet needs, and motivations to create solutions that truly resonate with your target audience.",
    pubDate: "2024-11-06",
    updatedDate: "2025-07-25",
    sequence: 23,
    contentType: "concepts",
    milestone: "milestone-3-evaluating-opportunities"
  },
  {
    slug: "sizing-up-your-opportunity",
    contentMetaId: "",
    programId: "b594dc90-3af0-4d62-9f5e-4b5dccba3fe9",
    title: "Sizing Up Your Opportunity",
    description: "Learn how to assess the market size, competition, and potential barriers to entry for your business opportunities.",
    milestone: "milestone-3-evaluating-opportunities",
    contentType: "concepts",
  }
];
